serve_port: 5300
auto_start: False
print_enable: True
log_enable: False
response_code:
  success: 0
  preparing: 1
  error: 3
signal_app_log_config:
  version: 1
  disable_existing_loggers: False  # 不覆盖默认配置
  formatters:
    default:
      format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  handlers:
    console:
      class: logging.StreamHandler
      level: DEBUG
      formatter: default
    log_file:
      class: logging.handlers.RotatingFileHandler
      level: INFO
      formatter: default  # 日志输出样式对应formatters
      filename: ./logs/flask_signal.log  # 指定log文件目录
      maxBytes: ${placeholder}  # 文件最大20M
      backupCount: 10  # 最多10个文件
      encoding: utf8
  root:
    level: DEBUG  # handler中的level会覆盖掉这里的level
    handlers:
      - console
      - log_file
UPLOAD_FOLDER: "./uploads"  # 设置合理的上传路径
MAX_CONTENT_LENGTH: 20  # 单位MB