# 服务配置
# host: 0.0.0.0
port: 5301
debug: True
upload_dir: ./uploads
max_file_size: 50  # MB

# 算法参数
default_decay_factor: 0.5
svd_rank: "auto"

# Swagger文档
swagger:
  title: EWT-SVD振动分析服务
  description: 
  version: 1.0.0